"""geom_column_added_in_organizations

Revision ID: 45ebfc02e4e3
Revises: 55fd22fbf2d8
Create Date: 2024-06-02 23:41:10.093894

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '45ebfc02e4e3'
down_revision: Union[str, None] = '55fd22fbf2d8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('organizations', sa.Column('geom', geoalchemy2.types.Geometry(geometry_type='POINT', srid=4326, from_text='ST_GeomFromEWKT', name='geometry'), nullable=True))
    op.create_index('idx_organizations_geom', 'organizations', ['geom'], unique=False, postgresql_using='gist')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_organizations_geom', table_name='organizations', postgresql_using='gist')
    op.drop_column('organizations', 'geom')
    # ### end Alembic commands ###
