"""added_new_tables

Revision ID: 5ece821d3618
Revises: 6173818791c5
Create Date: 2024-12-10 09:30:14.643135

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5ece821d3618'
down_revision: Union[str, None] = '6173818791c5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('charities',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip', sa.String(), nullable=True),
    sa.Column('irs_ein', sa.String(), nullable=True),
    sa.Column('ntee_code', sa.String(), nullable=True),
    sa.Column('last_researched_at', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('schools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('address', sa.String(), nullable=True),
    sa.Column('city', sa.String(), nullable=True),
    sa.Column('state', sa.String(), nullable=True),
    sa.Column('zip', sa.String(), nullable=True),
    sa.Column('last_researched_at', sa.String(), nullable=True),
    sa.Column('school_grade', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('colleges', sa.Column('name', sa.String(), nullable=True))
    op.add_column('colleges', sa.Column('address', sa.String(), nullable=True))
    op.add_column('colleges', sa.Column('city', sa.String(), nullable=True))
    op.add_column('colleges', sa.Column('state', sa.String(), nullable=True))
    op.add_column('colleges', sa.Column('zip', sa.String(), nullable=True))
    op.add_column('colleges', sa.Column('url', sa.String(), nullable=True))
    op.drop_constraint('colleges_organization_id_fkey', 'colleges', type_='foreignkey')
    op.drop_column('colleges', 'nces_data')
    op.drop_column('colleges', 'organization_id')
    op.drop_column('colleges', 'college_url')
    op.add_column('organizations', sa.Column('raw_org_id', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'raw_org_id')
    op.add_column('colleges', sa.Column('college_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('colleges', sa.Column('organization_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('colleges', sa.Column('nces_data', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_foreign_key('colleges_organization_id_fkey', 'colleges', 'organizations', ['organization_id'], ['id'])
    op.drop_column('colleges', 'url')
    op.drop_column('colleges', 'zip')
    op.drop_column('colleges', 'state')
    op.drop_column('colleges', 'city')
    op.drop_column('colleges', 'address')
    op.drop_column('colleges', 'name')
    op.create_table('spatial_ref_sys',
    sa.Column('srid', sa.INTEGER(), autoincrement=False, nullable=False),
    sa.Column('auth_name', sa.VARCHAR(length=256), autoincrement=False, nullable=True),
    sa.Column('auth_srid', sa.INTEGER(), autoincrement=False, nullable=True),
    sa.Column('srtext', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.Column('proj4text', sa.VARCHAR(length=2048), autoincrement=False, nullable=True),
    sa.CheckConstraint('srid > 0 AND srid <= 998999', name='spatial_ref_sys_srid_check'),
    sa.PrimaryKeyConstraint('srid', name='spatial_ref_sys_pkey')
    )
    op.drop_table('schools')
    op.drop_table('charities')
    # ### end Alembic commands ###
